# Generated by Django 4.2 on 2023-05-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('cover', models.ImageField(upload_to='static/resources/images')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('link', 'Link'), ('youtube', 'Youtube')], max_length=10)),
                ('name', models.CharField(default='', max_length=100)),
                ('link', models.URLField(default='')),
                ('block', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
