# Generated by Django 4.2 on 2023-05-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='course.course'),
        ),
        migrations.AlterField(
            model_name='item',
            name='block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='course.block'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('header', 'Header'), ('video', 'Video'), ('link', 'Link'), ('youtube', 'Youtube')], max_length=10),
        ),
    ]
