# Generated by Django 4.2 on 2023-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_item_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tab',
        ),
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
