# Generated by Django 4.2 on 2023-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_item_tab_block_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('paragraph', 'Paragraph'), ('header', 'Header'), ('pdf', 'pdf'), ('video', 'Video'), ('link', 'Link'), ('youtube', 'Youtube')], max_length=10),
        ),
    ]
