# Generated by Django 4.2 on 2023-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('header', 'Header'), ('pdf', 'pdf'), ('video', 'Video'), ('image', 'Image'), ('link', 'Link'), ('youtube', 'Youtube')], max_length=10),
        ),
    ]
